resources:
- icon: github
  name: apache-kafka-git
  source:
    uri: https://github.com/apache/kafka.git
  type: git

jobs:
- name: test
  public: true
  plan:
  - get: apache-kafka-git
    trigger: true
  - task: run-tests
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: gradle
          tag: jdk17
      caches:
        - path: $HOME/.m2/repository
        - path: $HOME/.gradle/caches/
        - path: $HOME/.gradle/wrapper/
      inputs:
        - name: apache-kafka-git
      run:
        user: root
        path: /bin/sh
        args:
          - -ce
          - |
            cd apache-kafka-git

            ./gradlew test
