---
resources:
- name: repo
  type: git
  icon: github
  source:
    uri: https://github.com/nodejs/nodejs.org.git

- name: node-image
  type: registry-image
  icon: docker
  source:
    repository: node
    tag: 22

jobs:
- name: test
  public: true
  plan:
  - get: node-image
  - get: repo
    trigger: true
  - task: install
    image: node-image
    config:
      inputs:
      - name: repo
      outputs:
      - name: workspace
        path: repo
      platform: linux
      run:
        path: npm
        args: ["ci", "--no-audit", "--no-fund"]
        dir: repo
  - task: test
    image: node-image
    config:
      inputs:
      - name: workspace
        path: repo
      platform: linux
      run:
        path: npm
        args: ["run", "test"]
        dir: repo
